konni
garowolflex/brend-coffee pull request #2
Opened 2019-08-10 11:08 UTC by tadashi05271218

konni

2019-08-10 11:30 UTC, garowolflex requested changes
「こんにちは」に対応して、最後に「さようなら」を追加してください。

2019-08-10 11:42 UTC, tadashi05271218 reviewed
みたら、わかるよｎ。。。。

2019-08-10 11:42 UTC, tadashi05271218 commented on test.rb
> +puts "さようなｒ"
惜しい。。。

2019-08-10 11:42 UTC, tadashi05271218 commented on test.rb
> +puts "さようなｒ"
いや、もうちょっ。。。

2019-08-10 11:43 UTC, garowolflex approved these changes
試しに Approve

2019-08-10 11:44 UTC, garowolflex requested changes
でもまぁ誤字ってるのでちゃんと修正をお願いします。

2019-08-10 11:44 UTC, garowolflex commented on test.rb
> +puts "さようなｒ"
「さようなら」だと言っていますよね。

2019-08-10 11:45 UTC, tadashi05271218 commented on test.rb
> +puts "さようなｒ"
ですよ(*´･ω･)(･ω･｀*)ﾈｰ

2019-08-10 11:50 UTC, garowolflex commented
競合が発生していますね。 ~~まぁそうするように仕向けたんですけど~~

* 今回の fix_test 変更差分は **masterに反映されているものを優先して表示** するように反映する
* ただし `exit 0` は最後になるように

2019-08-18 07:31 UTC, garowolflex commented
やっぱ要らないんで削除します。

2019-08-18 07:31 UTC, closed without merging